### ISSUE TITLE
Interface for the receptionist is scrollable.

### ISSUE THREAD

**Issue by Tomren3000** [Bitstackers/ReceptionistClient#96]
Can scroll down and back up in the interface of the receptionist client.

**Comment by rostgaard** [comment]
Please provide steps to reproduce.

**Comment by ThomasLocke** [comment]
I actually thinkg this one got fixed in one of your previous commits. I'm
fairly certain you can close it.

2015-02-03 20:04 GMT+01:00 Kim Rostgaard Christensen <
notifications@github.com>:

> Please provide steps to reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bitstackers/ReceptionistClient/issues/96#issuecomment-72712790>
> .
>



-- 
Med venlig hilsen
Thomas Løcke
Tlf.: +45 8832 9100
thomas@responsum.dk

www.responsum.dk
Responsum K/S @ Google+
<https://plus.google.com/108550532382892495740/posts>
